# config.yaml
# ----------------------------------------------------
# This file centralizes all configuration for the data pipeline.
# ----------------------------------------------------

# Parameters to define the specific study being run.
study_params:
  cancer_type: 'pancreas'

  cohort_definition_mode: 'predefined'
  
  
  # Controls
  start_date: '2011-01-01'
  controls_per_case: 5
  yob_window: 3

  map_to_icd10: false 

paths:

  #Predefined case file
  predefined_cases_file: '/data/WIPH-CanDetect/clean_data/cohort/cases_all_demographics.csv'
  
  # Main cancer registry file.
  raw_cancer_data: '/data/WIPH-CanDetect/intermediate_data/ncras/ncras_allcancers.dta'
  
  # Directory containing the patient demographic text files.
  raw_patient_data_dir: '/data/WIPH-CanDetect/raw_data_files/text_files/aurum/patient_txt/'
  
  # Central log file to track all subjects used across all studies.
  # The script will create this if it doesn't exist.
  master_subject_log: './master_subject_log.csv'

  # Path to the patient demographics file from NCRAS
  # This contains dobdate for more precise yob calculation.
  clean_ages_sex: '/data/WIPH-CanDetect/intermediate_data/ncras/clean_age_sex.dta'
  
  # Path to the Hospital Episode Statistics (HES) file for primary ethnicity
  hes_patient_data: '/data/WIPH-CanDetect/raw_data_files/text_files/aurum/linked_data_txt/e_aurum_hes_patient_23_002840_dm.txt'
  
  # Path to the ethnicity codelist
  ethnicity_codelist: '/data/WIPH-CanDetect/codelists/CPRD_Aurum_Codelist_Library/Demographics/CPRD_Aurum_ethnicity.dta'

  # Directory containing infor about practicies
  practice_data_dir: '/data/WIPH-CanDetect/raw_data_files/text_files/aurum/practice_txt/'
  
  # Directory containing the raw medical observation text files
  observation_data_dir: '/data/WIPH-CanDetect/raw_data_files/text_files/aurum/observation_txt/'

  # Directory containing the raw drug issue (medication) text files
  medication_data_dir: '/data/WIPH-CanDetect/raw_data_files/text_files/aurum/drug_issue_txt/'
  
  # Codelists and dictionaries needed for mapping event codes
  cleaned_codelists: '/data/home/qc25022/cancer-extraction-pipeline/src/resources/cleaned_code_lists8.csv'
  medical_dictionary: '/data/home/qc25022/PancreaticCancer/OutputFiles/MedicalDict.csv'
  product_dictionary: '/data/home/qc25022/PancreaticCancer/OutputFiles/ProdDict.csv'
  numunit_lookup: '/data/WIPH-CanDetect/documentation/lookups/aurum/NumUnit.txt'

  cleaning_rules_final: '/data/home/qc25022/cancer-extraction-pipeline/src/resources/cleaning_rules_final.csv'


  
# Paths for the output files generated by this study.
# Using the study name in the path helps keep results organized.
outputs:
  # The directory to save all outputs for this specific study.
  output_dir: './output/{cancer_type}_study/'
  
  # The final list of subject IDs and their case/control status for this study.
  cohort_file: './output/{cancer_type}_study/cohort.csv'

  subject_information_file: './output/{cancer_type}_study/subject_information.csv'

  intermediate_unsorted_dir: '/data/scratch/qc25022/{cancer_type}/intermediate_unsorted/'
  intermediate_sorted_dir: '/data/scratch/qc25022/{cancer_type}/intermediate_sorted/'

  # The final directory where patient-level Parquet files will be saved
  event_stream_dir: '/data/scratch/qc25022/{cancer_type}/event_streams/'

  profile_measurement: './output/{cancer_type}_study/profile_measurements.csv'
  cleaning_rules_template: './output/{cancer_type}_study/cleaning_rules_template.csv'
  

  final_cleaned_dir: '/data/scratch/qc25022/{cancer_type}/final_cleaned_events/'