# config.yaml
# ----------------------------------------------------
# This file centralizes all configuration for the data pipeline.
# ----------------------------------------------------

# Parameters to define the specific study being run.
study_params:
  # The cancer type to extract from the registry.
  # This should match the 'site' column in the raw_cancer_data file.
  cancer_type: 'liver'
  
  # The earliest diagnosis date for cases to be included.
  start_date: '2011-01-01'
  
  # The maximum number of controls to match to each case.
  controls_per_case: 5
  
  # The year-of-birth window for matching (e.g., 3 means +/- 3 years).
  yob_window: 3

  map_to_icd10: false # can be false as well
# Paths to the raw source data.
paths:
  # Main cancer registry file.
  raw_cancer_data: '/data/WIPH-CanDetect/intermediate_data/ncras/ncras_allcancers.dta'
  
  # Directory containing the patient demographic text files.
  raw_patient_data_dir: '/data/WIPH-CanDetect/raw_data_files/text_files/aurum/patient_txt/'
  
  # Central log file to track all subjects used across all studies.
  # The script will create this if it doesn't exist.
  master_subject_log: './master_subject_log.csv'

  # Path to the patient demographics file from NCRAS
  # This contains dobdate for more precise yob calculation.
  clean_ages_sex: '/data/WIPH-CanDetect/intermediate_data/ncras/clean_age_sex.dta'
  
  # Path to the Hospital Episode Statistics (HES) file for primary ethnicity
  hes_patient_data: '/data/WIPH-CanDetect/raw_data_files/text_files/aurum/linked_data_txt/e_aurum_hes_patient_23_002840_dm.txt'
  
  # Path to the ethnicity codelist
  ethnicity_codelist: '/data/WIPH-CanDetect/codelists/CPRD_Aurum_Codelist_Library/Demographics/CPRD_Aurum_ethnicity.dta'

  # Directory containing infor about practicies
  practice_data_dir: '/data/WIPH-CanDetect/raw_data_files/text_files/aurum/practice_txt/'
  
  # Directory containing the raw medical observation text files
  observation_data_dir: '/data/WIPH-CanDetect/raw_data_files/text_files/aurum/observation_txt/'

  # Directory containing the raw drug issue (medication) text files
  medication_data_dir: '/data/WIPH-CanDetect/raw_data_files/text_files/aurum/drug_issue_txt/'
  
  # Codelists and dictionaries needed for mapping event codes
  cleaned_codelists: '/data/home/qc25022/cancer-extraction-pipeline/src/resources/cleaned_code_lists8.csv'
  medical_dictionary: '/data/home/qc25022/PancreaticCancer/OutputFiles/MedicalDict.csv'
  product_dictionary: '/data/home/qc25022/PancreaticCancer/OutputFiles/ProdDict.csv'

  # Snomed to ICD10 map
  snomed_icd10_map: '/data/home/qc25022/cancer-extraction-pipeline/src/resources/snomed_to_ICD.txt'


  
# Paths for the output files generated by this study.
# Using the study name in the path helps keep results organized.
outputs:
  # The directory to save all outputs for this specific study.
  output_dir: './output/liver_study/'
  
  # The final list of subject IDs and their case/control status for this study.
  cohort_file: './output/liver_study/cohort.csv'

  subject_information_file: './output/liver_study/subject_information.csv'

  intermediate_unsorted_dir: '/data/scratch/qc25022/liver/intermediate_unsorted/'
  intermediate_sorted_dir: '/data/scratch/qc25022/liver/intermediate_sorted/'

  # The final directory where patient-level Parquet files will be saved
  event_stream_dir: '/data/scratch/qc25022/liver/event_streams/'
